// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineShop;

namespace WineShop.Migrations
{
    [DbContext(typeof(WineShopContext))]
    [Migration("20210516101654_initialData")]
    partial class initialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("WineShop.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageTypeId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("WineShop.PackageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PackageTypes");
                });

            modelBuilder.Entity("WineShop.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("WineTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WineTypeId");

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("WineShop.WinePackage", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "WineId");

                    b.HasIndex("WineId");

                    b.ToTable("WinePackage");
                });

            modelBuilder.Entity("WineShop.WineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WineType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dobro vino",
                            Name = "Chardonay"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dobro vino1",
                            Name = "Vino tipa 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dobro vino2",
                            Name = "Vino tipa 3"
                        });
                });

            modelBuilder.Entity("WineShop.Package", b =>
                {
                    b.HasOne("WineShop.PackageType", "PackageType")
                        .WithMany()
                        .HasForeignKey("PackageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageType");
                });

            modelBuilder.Entity("WineShop.Wine", b =>
                {
                    b.HasOne("WineShop.WineType", "WineType")
                        .WithMany()
                        .HasForeignKey("WineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WineType");
                });

            modelBuilder.Entity("WineShop.WinePackage", b =>
                {
                    b.HasOne("WineShop.Package", "Package")
                        .WithMany("Wines")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineShop.Wine", "Wine")
                        .WithMany("Packages")
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("WineShop.Package", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("WineShop.Wine", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
