// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineShop;

namespace WineShop.Migrations
{
    [DbContext(typeof(WineShopContext))]
    [Migration("20210514064226_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("WineShop.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("WineShop.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wines");
                });

            modelBuilder.Entity("WineShop.WinePackage", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId", "WineId");

                    b.HasIndex("WineId");

                    b.ToTable("WinePackage");
                });

            modelBuilder.Entity("WineShop.WinePackage", b =>
                {
                    b.HasOne("WineShop.Package", "Package")
                        .WithMany("Wines")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WineShop.Wine", "Vine")
                        .WithMany("Packages")
                        .HasForeignKey("WineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Vine");
                });

            modelBuilder.Entity("WineShop.Package", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("WineShop.Wine", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
